source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CBKContacts_Example', :exclusive => true do
  pod "CBKContacts", :path => "../"
end

target 'CBKContacts_Tests', :exclusive => true do
  pod "CBKContacts", :path => "../"

  pod 'Kiwi'
end
